#:schema ../../docs/host-options.schema.json

deviceType = "desktop"
repoPath = "/home/kieran/Documents/src/nixcfg"
systemType = "x86_64-linux"

office.enable = true
printing.enable = true

[networking]
hostName = "laptop"

[development]
enable = true
