# To add a new key from your SSH key:
# 1. Generate a private key
# Run `ssh-to-age -private-key ~/.ssh/id_ed25519 -o ~/.config/sops/age/keys.txt`
# 2. Generate a public key
# Run `ssh-to-age ~/.ssh/id_ed25519.pub`
# 3. Add the public key to the list of keys and appropriate creation rules
# This should be in the format of `&<hostname> <public key>`, which will start with `age1`
# DO NOT allow the private key to leave your machine

# To encrypt an existing file for a new key:
# Run `sops updatekeys <path to file>`
# This must run on a machine that already has access to the file

keys:
  - &canterbury age18klvxktm23sxs8fa8xts3kzzp8rwh9x037e98ym3sj2yuquqqs6sj3wy76
  - &rocinante age1ghp0654a5yrzgmyspanyvgp5lmz8tn4yqxjaa57kgejc8uuwh9fqnelusr
creation_rules:
  # Hosts
  - path_regex: hosts/rocinante/secrets.yaml$
    key_groups:
      - age:
          - *rocinante
  - path_regex: hosts/canterbury/secrets.yaml$
    key_groups:
      - age:
          - *canterbury

  # Users
  - path_regex: users/kieran/secrets.yaml$
    key_groups:
      - age:
          - *canterbury
          - *rocinante
