#:schema ../../docs/host-options.schema.json

deviceType = "desktop"
repoPath = "/home/kieran/Documents/src/nixcfg"
secrets.ageKeyFile = "/home/kieran/.config/sops/age/keys.txt"
systemType = "x86_64-linux"

games.enable = true

nvidia.enable = true

[networking]
hostName = "desktop"

[development]
enable = true
