'$schema' = "../../docs/generated/host-options.schema.json"

repoPath = "/home/kieran/src/nixcfg"

features.extras = true

docs.generateManCache = false # Takes over a minute on almost every rebuild.

[hardware]
memorySize = 8
raspberryPi.enable = true

[networking]
hostName = "tycho"
waitOnline = true

[server]
enable = true
hostname = "selwonk.uk"
data.baseDirectory = "/mnt/extern/data"

docs.enable = true
forgejo.enable = true
homepage.enable = true
immich.enable = true
paperless.enable = true
# search.enable = true # FIXME: This rebuilds everything, not just the index
trilium.enable = true
trilium.autoExport.enable = true
trilium.autoExport.remote = "ssh://forgejo@localhost/kieran/trilium-export.git"

[backup.repositories.server]
source = "/mnt/extern/data"
destination.local = "/mnt/extern/restic"
destination.remote = "backup/remote"

exclude = [
  "trilium/log", # Nothing we strongly care about
  # Daily copy-paste backups of the database
  # Since we're using a btrfs snapshot, SQLite can recover using
  # the WAL at any point in time and there is no race condition
  "trilium/backup",
]

# Required to run as root for btrfs snapshots
owner = "root"
password = "backup/password"
btrfs.useSnapshots = true
btrfs.snapshotPath = "/mnt/extern/backup-snapshot"
