'$schema' = "../../docs/generated/host-options.schema.json"

repoPath = "/home/kieran/src/nixcfg"

[hardware]
memorySize = 8
raspberryPi.enable = true

[networking]
hostName = "tycho"
waitOnline = true

[server]
enable = true
hostname = "selwonk.uk"
baseDataDir = "/mnt/extern/data"

docs.enable = true
trilium.enable = true
