'$schema' = "../../docs/generated/host-options.schema.json"

repoPath = "/home/kieran/src/nixcfg"

backup.enable = true

[hardware]
memorySize = 8
raspberryPi.enable = true

[networking]
hostName = "tycho"
waitOnline = true

[server]
enable = true
hostname = "selwonk.uk"
data.baseDirectory = "/mnt/extern/data"

docs.enable = true
trilium.enable = true

[backup.repositories.server]
source = "/mnt/extern/data"
destination.local = "/mnt/extern/restic"
destination.remote = "backup/remote"

exclude = ["trilium/log"]

# Required to run as root for btrfs snapshots
owner = "root"
password = "backup/password"
btrfs.useSnapshots = true
btrfs.snapshotPath = "/mnt/extern/backup-snapshot"
