'$schema' = "../../docs/generated/host-options.schema.json"

repoPath = "/home/kieran/Documents/src/nixcfg"

printing.enable = true

desktop.enable = true
desktop.environment = "gnome"

[backup.repositories.documents]
password = "backup/password"      # Path to the secret
owner = "kieran"
source = "/home/kieran/Documents"
# Exclude .git and src, as these are already tracked by git
exclude = [".git", "src"]
destination.local = "/home/kieran/Backups/Documents" # Local path
destination.remote = "backup/remote"                 # Path to the secret

[hardware]
memorySize = 8

powerSave.enable = true
powerSave.batteryOnly = true

[networking]
hostName = "canterbury"
