# Key bindings for AGS. Not done in nix as that would require grouping all binds by flags,
# which makes them harder to organize.
# Any binds that need non-standard packages should use variables set in nix.
# Flags:
# l -> locked, will also work when an input inhibitor (e.g. a lockscreen) is active.
# r -> release, will trigger on release of a key.
# e -> repeat, will repeat when held.
# n -> non-consuming, key/mouse events will be passed to the active window in addition to triggering the dispatcher.
# m -> mouse, see below
# t -> transparent, cannot be shadowed by other binds.
# i -> ignore mods, will ignore modifiers.

$leftMouse = mouse:272
$rightMouse = mouse:273
$middleMouse = mouse:274

# Lets start with the basics, this is standard for most tiling window managers.
# but Hyprland is the IKEA of window managers, so you have to assemble it yourself.
# Open the launcher with left windows key.
bindr = SUPER, SUPER_L, exec, $ags -t launcher

# Media keys
# TODO: Add a widget on change
# TODO: Get play/pause working somehow

# Volume, changing volume will also unmute
bind = ,XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = ,XF86AudioRaiseVolume, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
bind = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = ,XF86AudioLowerVolume, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ 0

bind = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle


# More advanced binds, these are more specific to my setup.

# Alt + left click to move windows
bindm = Alt, $leftMouse, movewindow
# Alt + right click to resize windows
bindm = Alt, $rightMouse, resizewindow
