[package]
name = "fdsearch"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive", "env"] }
eframe = "0.32.2"
egui_extras = "0.32.2"
thiserror = "2.0.16"
