'$schema' = "../../docs/generated/user-options.schema.json"

# Config to enable on all hosts

telly.enable = true

[userDetails]
email = "kieranknowles11@hotmail.co.uk"
firstName = "Kieran"
surName = "Knowles"

[games]
nexusModsKey = "nexusmods/apikey"
