{
  pkgs,
  config,
  lib,
  ...
}: {
  options.custom.office = let
    inherit (lib) mkEnableOption;
  in {
    enable = mkEnableOption "office suite";
  };

  config = lib.mkIf config.custom.office.enable {
    # Add templates for office applications, if we are installing a suite
    # These were generated by running the relevant applications and saving their blank files
    custom.desktop.templates = {
      "Document.odt" = ./templates/Document.odt;
      "Presentation.odp" = ./templates/Presentation.odp;
      "Spreadsheet.ods" = ./templates/Spreadsheet.ods;
    };

    custom.firefox.extraExtensions = [
      pkgs.firefox-addons.zotero-connector
    ];

    home.packages = with pkgs; [
      libreoffice
      # Needed for spell check
      hunspell
      # It's "Specialise" not "Specialize", we're British
      hunspellDicts.en_GB-ise

      # Research
      zotero
    ];
  };
}
