# TODO: Move all libreoffice to home-manager
{
  hostConfig,
  lib,
  ...
}: {
  config = lib.mkIf hostConfig.custom.office.enable {
    # Add templates for office applications, if we are installing a suite
    # These were generated by running the relevant applications and saving their blank files
    custom.desktop.templates = {
      "Document.odt" = ./templates/Document.odt;
      "Presentation.odp" = ./templates/Presentation.odp;
      "Spreadsheet.ods" = ./templates/Spreadsheet.ods;
    };
  };
}
