#:schema ../../docs/generated/host-options.schema.json

deviceType = "desktop"
repoPath = "/home/kieran/Documents/src/nixcfg"

games.enable = true

nvidia.enable = true

backup.enable = true
[backup.repositories.documents]
password = "backup/password"
owner = "kieran"
source = "/home/kieran/Documents"
# Exclude .git and src, as these are already tracked by git
exclude = [ ".git", "src" ]
destination = "/home/kieran/Backups/Documents"

[backup.repositories.documents-remote]
password = "backup/password"
owner = "kieran"
source = "/home/kieran/Documents"
destination = "backup/remote"
exclude = [ ".git", "src" ]
destinationIsSecret = true

[networking]
hostName = "rocinante"

[development]
enable = true
