'$schema' = "../../docs/generated/host-options.schema.json"

features.desktop = true
repoPath = "/home/kieran/Documents/src/nixcfg"

ledState.enable = true

nvidia.enable = true
vr.enable = true

backup.enable = true
[backup.repositories.documents]
password = "backup/password"
owner = "kieran"
sources = ["/home/kieran/Documents"]
# Exclude .git and src, as these are already tracked by git
exclude = [".git", "src"]
destination.local = "/home/kieran/Backups/Documents"
destination.remote = "backup/remote"

[hardware]
memorySize = 32

[networking]
hostName = "rocinante"

[development]
enable = true

[cache]
mode = "send"
send.privateKeySecret = "cache/privateKey"
